all:
  children:
    lxc_containers:
      hosts:
        pihole.dns.puvvadi.net:
        guard.dns.puvvadi.net:
        esphome.dns.puvvadi.net:
        metrics.dns.puvvadi.net:
        otf.dns.puvvadi.net:
        pg.dns.puvvadi.net:
        speed.dns.puvvadi.net:
        z2m.dns.puvvadi.net:
        odin.dns.puvvadi.net:
        home.puvvadi.net:
    virtual_machines:
      hosts:
        media.puvvadi.net:
    raspberry_pi:
      hosts:
        yggdrasil.dns.puvvadi.net:
