all:
  children:
    lxc_containers:
      hosts:
        pihole.dns.puvvadi.net:
        guard.dns.puvvadi.net:
        esphome.dns.puvvadi.net:
        metrics.dns.puvvadi.net:
        otf.dns.puvvadi.net:
        pg.dns.puvvadi.net:
        speed.dns.puvvadi.net:
        z2m.dns.puvvadi.net:
        dns.puvvadi.net:
    virtual_machines:
      hosts:
        docker.dns.puvvadi.net:
        media.puvvadi.net:
    # raspberry_pi:
    #   hosts:
    #     dns.puvvadi.net:
